### ISSUE TITLE
Problema con token recién creado

### ISSUE THREAD

**Issue by vktrGit** [culqi/culqi-java#16]
Cuando creo un token desde mi pagina web y la envío a mi servidor para crear una tarjeta me sale el siguiente mensaje de error "No existe el siguiente token_id: 'tkn_test_xpzdawRxC1I8JZat'."
Tengo entendido que los tokens duran 5min, pero no demoro ni 1 min en enviarlo para la creación de una tarjeta. He intentado enviar el token de muchas maneras y el resultado es el mismo. EL lenguaje que uso es Java.

**Comment by KeidenKs** [comment]
Yo tengo el mismo problema lo lograstes solucionar???

**Comment by garysve** [comment]
Por si no lograron solucionarlo, tuve el mismo problema y lo solucioné de la siguiente manera:
La url que estaba usando para crear el Token era esta: https://api.culqi.com/v2, cuando la correcta y actualizada es esta: https://secure.culqi.com/v2. Esa url, es SOLO PARA CREAR EL TOKEN, con eso lo pude solucionar.
