### ISSUE TITLE
Translate Readme.md to English

### ISSUE THREAD

**Issue by william-muro-culqi** [culqi/culqi-java#6]
Translate the Readme.md to English in the file Readme_EN.md

**Comment by iCueto** [comment]
I would like to work on this issue

**Comment by william-muro-culqi** [comment]
Thanks @iCueto

**Comment by iCueto** [comment]
@jeancedron, has made a PR with the file Readme_en.md, please accept that PR to work on this issue...

-Thank! :>

**Comment by william-muro-culqi** [comment]
@iCueto @jeancedron Done!

**Comment by iCueto** [comment]
Thank!

**Comment by iCueto** [comment]
@william-muro Readme Translated! 👍

**Comment by marti1125** [comment]
greaT!!
